import { useForm, ValidationError } from '@formspree/react';
import { useState } from 'react';
import { ArrowUpRight, Check } from 'lucide-react';
import Reveal from './Reveal';
import Turnstile from './Turnstile';

const TURNSTILE_SITEKEY = '0x4AAAAAAEsYnQEyqgsLP23W';

export default function Contact() {
  const [state, handleSubmit] = useForm('xaeypzll');
  const [token, setToken] = useState('');
  return <section className="contact-section" id="contact"><div className="section-pad contact-grid"><Reveal><span className="eyebrow cyan-text">10 / START A CONVERSATION</span><h2>Ready to<br /><em>weave your data?</em></h2><p>Tell us where your data journey is today. We'll help you see the next clear move.</p><div className="contact-detail"><span className="status-dot" /> DATAWEAVEX / 2026</div><div className="contact-offices"><div className="office-card"><span className="eyebrow">SRI LANKA — HQ</span><strong>DataWeavex PVT LTD</strong><span>No. 02 Union Place, Colombo 00200</span><a href="tel:+94718373531">+94 71 837 3531</a></div><div className="office-card"><span className="eyebrow">UNITED STATES</span><strong>DataWeavex LLC</strong><span>24 Waverly Pl, New York, NY 10003, USA</span><a href="tel:+14844458251">+1 484 445 8251</a></div><div className="office-card"><span className="eyebrow">EMAIL</span><a href="mailto:contact@dataweavex.net">contact@dataweavex.net</a></div></div></Reveal><Reveal delay={0.1}><form className="contact-form" onSubmit={handleSubmit}><div className="form-row"><label>Name<input name="name" required placeholder="Enter your name" /></label><label>Company<input name="company" required placeholder="Enter your company name" /></label></div><label>Business email<input name="email" required type="email" placeholder="Enter your work email" /><ValidationError className="form-error" field="email" errors={state.errors} /></label><div className="form-row"><label>Company size<select name="company_size" defaultValue=""><option value="" disabled>Select size</option><option>1–50</option><option>51–500</option><option>501–5,000</option><option>5,000+</option></select></label><label>Data environment<select name="data_environment" defaultValue=""><option value="" disabled>Select environment</option><option>Cloud</option><option>Hybrid</option><option>On-premise</option><option>Multi-cloud</option></select></label></div><label>Message<textarea name="message" required placeholder="Enter your message" rows={4} /><ValidationError className="form-error" field="message" errors={state.errors} /></label><input type="hidden" name="cf-turnstile-response" value={token} /><Turnstile siteKey={TURNSTILE_SITEKEY} onToken={setToken} /><button className="button button-primary" type="submit" disabled={state.submitting || !token}>{state.submitting ? 'Sending...' : 'Start a conversation'} <ArrowUpRight size={16} /></button>{state.succeeded && <span className="form-success"><Check size={14} /> Thanks — we'll be in touch.</span>}</form></Reveal></div></section>;
}